spring:
  datasource:
    password: 12345
    username: remote
    url: jdbc:mysql://192.168.1.148:3306/fornecedor?useTimezone=true&serverTimezone=America/Sao_Paulo
  jpa:
    hibernate:
      ddl-auto: update
